### ISSUE TITLE
A parent node should be made and added in index array if it is not present in array and we are asked to add a child node to it.

### ISSUE THREAD

**Issue by raovikash** [sabotuer99/HackerRank-Java#1]
Therefore code in lines 70-71 should be as follows-
if(YN==null){
            YN=new Node(Y);
    }

**Comment by sabotuer99** [comment]
Which file did you find this in?

**Comment by sabotuer99** [comment]
So I believe you are talking about the Kth Ancestor code:
HackerRank-Java/HackerRank/src/algorithms/graphtheory/KthAncestor.java

I haven't looked at this code in ages, and it managed to pass the HR tests.  I will say that when I compared my code to other solutions, mine was pretty inelegant.  

It still passes all the test cases with your suggested change, but I'm not inclined to go in and fix it in the repo.  Thanks for the feedback though.
